#############################################################
##### Configuration File for JWST Coronagraphy Pipeline #####
#############################################################

# TODO: Create readthedocs page that describe each setting in detail. 

#######################
##### Directories #####
#######################

##### REQUIRED #####
# Input Directory 
idir: '/Users/valentin/Documents/JWST/jwst_s1s2_data/pynrc_data/'
odir: '/Users/valentin/Documents/JWST/jwst_s1s2_data/tuto_test/' # Output Directory
sdir: '/Users/acarter/Documents/DIRECT_IMAGING/CORONAGRAPHY_PIPELINE/HIP65426.vot' #VOT table or stellar model file.

##### OPTIONAL #####
rundirs: []  #Specify directory(ies) within odir of existing runs to calculate contrast curve / companion
ancildir: None      # Specify directory to save ancillary files, if None then saved under odir/ANCILLARY/. 

############################
##### General Settings #####
############################
verbose: True 
plotting: True    # Produce matplotlib plots
use_psfmask: True # if true use PSF masks from CRDS, if false use transmission functions
fiducial_point_override: True # if true uses narrow end of the bar masks, if false use filter dependent position
overwrite: True   # Will overwrite existing files in a given directory

########################################
##### Star / Companion information #####
########################################
spt: 'A2V' # Spectral type of target, only necessary for VOTable. Keep it simple.
ra_off: [418.] # mas; RA offset of the known companions
de_off: [-698.] # mas; DEC offset of the known companions 

#################################
##### Ramp Fitting Settings #####
#################################
ramp_ext: 'uncal.fits'
skip_jump: False     #Whether to skip the jump detection step of the pipeline
jump_threshold: 20   #Adjust the jump detection threshold if not skipped2022_06_27_RDI_annu1_subs1_run2'

#####################################
##### Image Processing Settings #####
#####################################
imgproc_ext: 'rateints.fits'

####################################
##### PSF Subtraction Settings #####
####################################
sub_ext: 'calints.fits'
centering_alg: "jwstpipe"    # Algorithm to use for centering "basic", "jwstpipe", or "imageregis" 
mode: ['RDI']       # list of modes for pyKLIP, will loop through all
annuli: [1]         # list of number of annuli for pyKLIP, will loop through all
subsections: [1]    # list of number of annuli for pyKLIP, will loop through all
numbasis: [1, 2, 5, 10, 20, 50, 100] # list of number of basis vectors for pyKLIP, will loop through all

###################################
##### Contrast Curve Settings #####
###################################
KL: 10 # Number of KL components for which the calibrated contrast curve and the companion properties shall be computed (must be in subtracted numbasis)

seps_inject_rnd: [5.0, 7.5, 10.0, 12.5, 15.0, 17.5, 20.0, 25., 30.0, 35.0, 40.0] # pix; list of separations at which fake planets shall be injected to compute the calibrated contrast curve for the round masks
pas_inject_rnd: [0., 45., 90., 135., 180., 225., 270., 315.] # deg; list of position angles at which fake planets shall be injected to compute the calibrated contrast curve for the round masks

pa_ranges_bar: [(105, 105), (285, 285)] # deg; list of tuples defining the pizza slices that shall be considered when computing the contrast curves for the bar masks
seps_inject_bar: [2.0, 4.0, 6.0, 8.0, 10.0, 12.5, 15.0, 17.5, 20.0, 25.0, 30.0] # pix; list of separations at which fake planets shall be injected to compute the calibrated contrast curve for the bar masks
pas_inject_bar: [45., 135., 225., 315.] # deg; list of position angles at which fake planets shall be injected to compute the calibrated contrast curve for the bar masks

seps_inject_fqpm: [5, 7.5, 10.0, 12.5, 15.0, 17.5, 20.0, 25., 30.0, 35.0, 40.0]
pas_inject_fqpm: [45., 135., 225., 315.]

#######################################################
##### Companion Photometry / Astrometry Settings ######
#######################################################
nwalkers:  100
nburn: 100
nsteps: 200
numthreads: 2



