name: CI

on: [push, pull_request]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - name: Check for Sphinx doc build errors
            os: ubuntu-latest
            python: 3.10
            toxenv: docbuild

          - name: Try latest versions of all dependencies
            os: ubuntu-latest
            python: '3.11'
            toxenv: py311-latest-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install Python dependencies
      run: pip install tox tox-conda>=0.2

    - name: Install specific branches of pyklip and webbpsf_ext
      run: pip install git+https://github.com/JarronL/webbpsf_ext.git@develop
           pip install git+https://bitbucket.org/pyKLIP/pyklip.git@jwst

    - name: Get WebbPSF Data
      run: | # Get WebbPSF data files (just a subset of the full dataset!) and set up environment variable
           wget https://stsci.box.com/shared/static/ykkvequ9cbble6qg88ldhjoep4m9ey6x.gz -O /tmp/minimal-webbpsf-data.tar.gz
           tar -xzvf /tmp/minimal-webbpsf-data.tar.gz
           echo "WEBBPSF_PATH=${{github.workspace}}/webbpsf-data" >> $GITHUB_ENV

    - name: Check conda info
      run: conda info

    - name: Run tests with requirements file
      if: ${{ contains(matrix.toxenv,'-latest') }}
      run: |
        cp $RUNNER_WORKSPACE/spaceKLIP/requirements.txt /tmp/
        tox -e ${{ matrix.toxenv }}

    - name: Run tests
      if: ${{ matrix.continue-on-error == null && contains(matrix.toxenv,'-latest') != true }}
      run: tox -e ${{ matrix.toxenv }}

    - name: Run tests and allow failures
      if: matrix.continue-on-error
      continue-on-error: true
      run: tox -e ${{ matrix.toxenv }}

    - name: Upload coverage to codecov
      if: ${{ contains(matrix.toxenv,'-cov') }}
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
